export const config = {
    MAPBOX_SEARCH_API_URL: process.env.NEXT_PUBLIC_MAPBOX_API_URL,
    MAPBOX_SEARCH_TYPE: process.env.NEXT_PUBLIC_MAPBOX_SEARCH_TYPE,
    MAPBOX_SESSION_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_SESSION_TOKEN,
    MAPBOX_API_KEY: process.env.NEXT_PUBLIC_MAPBOX_API_KEY,

    OPENWEATHER_API_URL: process.env.NEXT_PUBLIC_OPENWEATHER_API_URL,
    OPENWEATHER_API_KEY: process.env.NEXT_PUBLIC_OPENWEATHER_API_KEY,
    OPENWEATHER_ICON_URL: process.env.NEXT_PUBLIC_OPENWEATHER_ICON_URL,
    OPENWEATHER_ICON_EXTENSION: process.env.NEXT_PUBLIC_OPENWEATHER_ICON_EXTENSION,
};